apiVersion: apps/v1
kind: Deployment
metadata:
  name: timaoapp
spec:
  selector:
    matchLabels:
      run: timaoapp
  replicas: 2
  template:
    metadata:
      labels:
        run: timaoapp
    spec:
      containers:
      - name: timaoapp
        image: guilhermeacc/timaoapp:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: timaoapp
  labels:
    run: timaoapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: timaoapp